redshift:
  target: dev
  outputs:
    dev:
      type: redshift
      method: iam
      cluster_id: dbt-redshift-cluster
      host: dbt-redshift-cluster.cfntbvlxunrl.ap-southeast-1.redshift.amazonaws.com
      user: admin
      iam_profile: default # optional
      # iam_duration_seconds: 900  # optional
      # autocreate: true           # optional
      # db_groups: ['ANALYSTS']    # optional

      # Other Redshift configs:
      port: 5439
      dbname: dev
      schema: dbt
      # threads: 4
      # [keepalives_idle](#keepalives_idle): 240 # default 240 seconds
      # connect_timeout: 10 # default 10 seconds
      # [retries](#retries): 1 # default 1 retry on error/timeout when opening connections
      # # search_path: public # optional, but not recommended
      # sslmode: [optional, set the sslmode used to connect to the database (in case this parameter is set, will look for ca in ~/.postgresql/root.crt)]
      # ra3_node: true # enables cross-database sources
